### PR TITLE
Updated code for only used functionalities and tailored to GISAID input

### PR DESCRIPTION
**Pull request by EvaFriederike**
Changes include:

- tailored to processing GISAID data as input for reference reconstruction; removed code that was aimed at processing DESH data (was all no used anyways)
- removed other unused/obsolete code
- use full file paths everywhere , because using $projectDir in nextflow processes caused "file not found" issues when running on hpc
- groomed readme

### CODE REVIEW

**Comment by hoelzer** [comment]
very weird I got this error during execution and don't know why:

```bash
ERROR ~ Input length = 1

 -- Check '.nextflow.log' file for details
```

It works always until a certain point:

```bash
executor >  local (91)
[b3/61047f] process > process_input_data:process_gisaid (1)         [100%] 2 of 2 ✔
[13/93239e] process > build_reference_db:filter_by_metadata (2)     [100%] 2 of 2 ✔
[16/626016] process > build_reference_db:filter_sequences (86)      [ 41%] 86 of 209
[cf/76de33] process > build_reference_db:variant_call (2)           [  0%] 0 of 171
[-        ] process > build_reference_db:merge_vcf                  -
[-        ] process > build_reference_db:filter_by_aaf              -
[-        ] process > build_reference_db:filter_sequences_by_aaf    -
[-        ] process > predict_abundances:build_index                -
[-        ] process > predict_abundances:kallisto_prediction_single -

ERROR ~ Input length = 1

 -- Check '.nextflow.log' file for details
```

and then this error. 

Maybe it's bc I am on my mac? Sometimes that causes weird issues. 

I found this thread: https://github.com/nextflow-io/nextflow/issues/149. It seems that it might have something to do with the encoding. Maybe that's why people here in Ukraine simulate files using a weird encoding. Hm... but no all encoding is actually

`fastq-input/sample1_R1.fastq: text/plain; charset=us-ascii`

for my input FASTQ and reference files. 

```bash
nextflow run VLQ-nf/main.nf --gisaid /Users/martin/projects/2024-07-10-EEBG-vlq-nf/reference-data --query /Users/martin/projects/2024-07-10-EEBG-vlq-nf/fastq-input -w work
```

From the `.nextflow.log`


```bash
Jul-10 19:03:27.774 [Actor Thread 8] DEBUG n.splitter.AbstractTextSplitter - Splitter `Fasta` collector path: nextflow.splitter.TextFileCollector$CachePath(/Users/martin/projects/2024-07-10-EEBG-vlq-nf/work/4d/5cc2077ab0235f2c80445737a8524d/sample.fasta, null)
Jul-10 19:03:27.782 [Actor Thread 8] ERROR nextflow.extension.DataflowHelper - @unknown
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:213)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at java.base/java.io.Reader.read(Reader.java:250)
	at nextflow.splitter.AbstractTextSplitter.positionAfterBOM(AbstractTextSplitter.groovy:335)
	at nextflow.splitter.AbstractTextSplitter.normalizeSource(AbstractTextSplitter.groovy:114)
	at nextflow.splitter.AbstractTextSplitter.normalizeSource(AbstractTextSplitter.groovy)
	at nextflow.splitter.AbstractSplitter.apply(AbstractSplitter.groovy:153)
	at nextflow.extension.SplitOp$_applySplittingOperator_closure1.doCall(SplitOp.groovy:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.DataflowHelper$_subscribeImpl_closure2.doCall(DataflowHelper.groovy:284)
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Jul-10 19:03:27.786 [Actor Thread 8] DEBUG nextflow.Session - Session aborted -- Cause: Input length = 1
Jul-10 19:03:27.795 [Actor Thread 8] DEBUG nextflow.Session - The following nodes are still active:
```

**Comment by hoelzer** [comment]
Alright, I also accidentally had two CSV in the reference folder, and Nextflo picked up both. Now I cleaned that. So, at least the error changed:

```bash
[a7/0ac789] process > build_reference_db:variant_call (27)          [ 38%] 19 of 50, failed: 1
[-        ] process > build_reference_db:merge_vcf                  -
[-        ] process > build_reference_db:filter_by_aaf              -
[-        ] process > build_reference_db:filter_sequences_by_aaf    -
[-        ] process > predict_abundances:build_index                -
[-        ] process > predict_abundances:kallisto_prediction_single -
ERROR ~ Error executing process > 'build_reference_db:variant_call (24)'

Caused by:
  Process `build_reference_db:variant_call (24)` terminated with an error exit status (1)

Command executed:

  ##############################################
  # Source: https://github.com/baymlab/wastewater_analysis
  #############################################

  echo "Call variants for fasta chunk gisaid_sample.24"

  PAF=$(which paftools.js)
  mkdir -p fasta/

  echo "Split multifasta and collect lineage annotation"
  split_fasta_collect_lineage.py -meta selection_by_metadata.csv -multifasta filtered_sample.24.fasta

  for file in fasta/*.fasta; do
    basename=${file##*/}
    fasta_id=${basename%.fasta}
    lineage=${fasta_id%%_*}

    minimap2 -c -x asm20 --end-bonus 100 -t 20 --cs NC_045512.2.fasta $file 2>${fasta_id}.paftools.log | sort -k6,6 -k8,8n > ${fasta_id}.paf && ${PAF} call -s $fasta_id -L 100 -f NC_045512.2.fasta ${fasta_id}.paf > ${fasta_id}.vcf 2>>${fasta_id}.paftools.log;
    bgzip -f ${fasta_id}.vcf;
    bcftools index -f ${fasta_id}.vcf.gz;
    mv  ${fasta_id}.vcf*  ${fasta_id}.paf* fasta/$lineage
  done

  touch gisaid_sample.24_lineages.txt
  for dir in fasta/*; do
    if [ -d ${dir} ]; then
      lineage=${dir##*/}
      echo merge vcf files for lineage ${lineage}
      echo $lineage >> gisaid_sample.24_lineages.txt

      sample_count=$(ls ${dir}/*.vcf.gz | wc -l);
      if [[ $sample_count -eq 1 ]]; then
        cp ${dir}/*.vcf.gz ${lineage}_gisaid_sample.24_merged.vcf.gz
      else
        bcftools merge -o ${lineage}_gisaid_sample.24_merged.vcf.gz -O z $dir/*.vcf.gz
      fi
    fi
  done

  touch gisaid_sample.24_paftools.log
  #touch gisaid_sample.24_samples.txt
  cat .command.log >> gisaid_sample.24_paftools.log
  for file in fasta/*/*paftools.log; do
    cat $file >> gisaid_sample.24_paftools.log
    #filename=${file##*/}
    #tmp_filename=${filename#*_}
    #echo ${tmp_filename%.paftools.log}>> gisaid_sample.24_samples.txt
  done

Command exit status:
  1

Command output:
  Call variants for fasta chunk gisaid_sample.24
  Split multifasta and collect lineage annotation
  read data
  parse multifasta records, get lineage and write to fasta

Command error:
  Call variants for fasta chunk gisaid_sample.24
  Split multifasta and collect lineage annotation
  read data
  parse multifasta records, get lineage and write to fasta

Work dir:
  /Users/martin/projects/2024-07-10-EEBG-vlq-nf/work/bb/909b4b8a6dcda4c885f3f8c8a52f61
```

but still cant get behind it o_O

**Comment by hoelzer** [comment]
I think this could be merged and then released, or @EvaFriederike ?

**Review by hoelzer — APPROVED** [review]

**Comment by JinchaoChen112** [comment]
> ```shell
> ta` collector path: nextflow.splitter.TextFileCollector$CachePath(/Users/martin/projects/2024-07-10-EEBG-vlq-nf/work/4d/5cc2077ab0235f2c80445737a8524d/sample.fasta, null)
> Jul-10 19:03:27.782 [Actor Thread 8] ERROR nextflow.extension.DataflowHelper - @unknown
> ```

I also have this problem. How can it be resolved? I don't have a duplicate input CSV file.

**Comment by hoelzer** [comment]
Hey @JinchaoChen112 sorry to hear that you have a problem with the pipeline. But this is a closed Pull Request, can you please make a new https://github.com/rki-mf1/VLQ-nf/issues and describe how you are installing/starting the pipeline and what the error is? Then we can see if we can help. Thanks!

**Pull request merged**
